Desktop-version
KAYEMBAJONATHAN/mydestop_pro pull request #4
Opened 2023-02-23 05:57 UTC by KAYEMBAJONATHAN

.This is my desktop version 
.Update README. md
.I Readapt the style.css
.fix html file add some new img

2023-02-23 06:50 UTC, wayungi requested changes
Hi @KAYEMBAJONATHAN , 
![image](https://user-images.githubusercontent.com/99656687/220082777-7a0e6a7f-854d-4e32-9c38-3b1eb3b090e4.png)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Profesional README ✔️ 
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔
- [ ] No merge conflicts ✔️ 
- [ ]  Correct GitHub flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Between your projects and the `about myself` section, your background color cannot be seen. Please add it back. check image below for clarification.
**design**
![dez1](https://user-images.githubusercontent.com/99656687/220837437-1f341c0b-060a-4546-9dea-1fd496261b3b.png)
**Your implementation**
![dez2](https://user-images.githubusercontent.com/99656687/220837482-a8f0f2e7-a6ee-4b3c-aeef-9347994a61fc.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 06:50 UTC, wayungi commented on index.html
> +      <img src="./assets/Snapshoot Portfolio.png" alt="project card image" />
- [ ] For all your project cards, they are not fully matching the figma design. Please take a look at the images below to compare and contrast and the fix the issues by tweaking your margin or padding to match the design.

**figma**
![des1](https://user-images.githubusercontent.com/99656687/220836572-4a9d0c02-91cb-4e3a-b95e-8da04be1c73d.png)
**Your implementation**
![des2](https://user-images.githubusercontent.com/99656687/220836603-ff644e34-e8fa-4d69-b4a6-f750ac2aeb93.png)

2023-02-23 19:08 UTC, Zuhaib042 requested changes
Hi @KAYEMBAJONATHAN , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![close](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

 ## Highlights
✅ Professional Readme
✅ Professional PR
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 19:08 UTC, Zuhaib042 commented on index.html
>    <section class="project-container">
- [ ] As the previous reviewer mentioned about the background-color of the sections and cards should be similar to the figma design. The origin of the problem for this is line no `47` in your style.css where you are styling your `section tag` generally. kindly consider removing that line and then give the `hero section` and the `about me` section background-color of `#fff`
your design
![re](https://user-images.githubusercontent.com/96683843/221005923-bc03bcae-bce3-4c5c-8c15-b5f6fd399242.jpg)
![fd](https://user-images.githubusercontent.com/96683843/221005939-de2578b9-7d6d-4bd8-a2f3-709439a3a987.jpg)

figma design
![qw](https://user-images.githubusercontent.com/96683843/221005771-1292ec61-7d2a-4bc2-804d-a5d6215e1e94.jpg)
![zx](https://user-images.githubusercontent.com/96683843/221005852-87265bec-470a-4fa0-a703-87f1a09f0ffd.jpg)

2023-02-24 09:23 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @KAYEMBAJONATHAN , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/9ab1354ab399a31c604186cd2e7c09a0d4704215a1eda3e29a02fc52bf3f6bf5/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d474b31673838485a526132466c4b47627a2f67697068792e676966)

## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x]  GitHub flow is used correctly :white_check_mark: 
- [x] Implemented all the changes from the previous reviewer :white_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 09:36 UTC, merged